{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-amqp",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-amqp-3.4.1.jar",
          "url": "spring-boot-starter-amqp-3.4.1.jar",
          "size": 4752,
          "sha512": "d8f1e02485e41abe78b1663c0e657db792e3206d9380878000c1b08f626ed7dfc3518cf68554262d233d8f3eeb1eb0939dcb70c1759845301e04b2191354eb7c",
          "sha256": "6389ea09213618ebe2ccc3211171983bb9c4b0e46c479dcf1040b4402c6263b2",
          "sha1": "490eae1ecdb47be588339508823be8c5dee949ec",
          "md5": "2914b0626e7dba9b33a1f772c1c083fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-amqp-3.4.1.jar",
          "url": "spring-boot-starter-amqp-3.4.1.jar",
          "size": 4752,
          "sha512": "d8f1e02485e41abe78b1663c0e657db792e3206d9380878000c1b08f626ed7dfc3518cf68554262d233d8f3eeb1eb0939dcb70c1759845301e04b2191354eb7c",
          "sha256": "6389ea09213618ebe2ccc3211171983bb9c4b0e46c479dcf1040b4402c6263b2",
          "sha1": "490eae1ecdb47be588339508823be8c5dee949ec",
          "md5": "2914b0626e7dba9b33a1f772c1c083fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-amqp-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-amqp-3.4.1-javadoc.jar",
          "size": 4752,
          "sha512": "d8f1e02485e41abe78b1663c0e657db792e3206d9380878000c1b08f626ed7dfc3518cf68554262d233d8f3eeb1eb0939dcb70c1759845301e04b2191354eb7c",
          "sha256": "6389ea09213618ebe2ccc3211171983bb9c4b0e46c479dcf1040b4402c6263b2",
          "sha1": "490eae1ecdb47be588339508823be8c5dee949ec",
          "md5": "2914b0626e7dba9b33a1f772c1c083fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-amqp-3.4.1-sources.jar",
          "url": "spring-boot-starter-amqp-3.4.1-sources.jar",
          "size": 4752,
          "sha512": "d8f1e02485e41abe78b1663c0e657db792e3206d9380878000c1b08f626ed7dfc3518cf68554262d233d8f3eeb1eb0939dcb70c1759845301e04b2191354eb7c",
          "sha256": "6389ea09213618ebe2ccc3211171983bb9c4b0e46c479dcf1040b4402c6263b2",
          "sha1": "490eae1ecdb47be588339508823be8c5dee949ec",
          "md5": "2914b0626e7dba9b33a1f772c1c083fe"
        }
      ]
    }
  ]
}
