{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.amqp",
    "module": "spring-amqp",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-amqp-3.2.1.jar",
          "url": "spring-amqp-3.2.1.jar",
          "size": 162345,
          "sha512": "b2d7c1b794591163fa76df4e1989fd42a4875eed08ab2a9f43e4c343118178c73f4027e69bc6180473ca3f2edfd9c26312f6cbb40858f9c1ecabe4c1ecbc50fd",
          "sha256": "0b080030af2693f689a170da0d3d9b067aa178871273cbef3f087816e976be0c",
          "sha1": "401d228d7adeb11ae037dc3bd8317feac88a8490",
          "md5": "48fdc5551c0d492d8f12241e210dc6d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-amqp-3.2.1.jar",
          "url": "spring-amqp-3.2.1.jar",
          "size": 162345,
          "sha512": "b2d7c1b794591163fa76df4e1989fd42a4875eed08ab2a9f43e4c343118178c73f4027e69bc6180473ca3f2edfd9c26312f6cbb40858f9c1ecabe4c1ecbc50fd",
          "sha256": "0b080030af2693f689a170da0d3d9b067aa178871273cbef3f087816e976be0c",
          "sha1": "401d228d7adeb11ae037dc3bd8317feac88a8490",
          "md5": "48fdc5551c0d492d8f12241e210dc6d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-amqp-3.2.1-javadoc.jar",
          "url": "spring-amqp-3.2.1-javadoc.jar",
          "size": 556558,
          "sha512": "812421dae189a614ee62ec0f4a852dd2b124a694b3d373dda7911423f3e951dffed316e9ddd427f0f7e2e1de7ac103abe222ccda7df5aa68f74b86eedfa70975",
          "sha256": "d8f42c721afc21c21cd28ec1eaa3de8228d946c244d8ccd4a387609489947b8e",
          "sha1": "3e53ce955f862c318172c57efdddd9d8ed271f71",
          "md5": "a812fed7b5e3e1119df1cc9d6c874e21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-amqp-3.2.1-sources.jar",
          "url": "spring-amqp-3.2.1-sources.jar",
          "size": 143316,
          "sha512": "85ed401bbd45bba0eb7aed9a259ec8e7a0c669df90e56e0a09ff7340f3bf79be6c120714154694f9761e8008363af38b064e83b892f6f81fffc8476cdc246519",
          "sha256": "c7b8ac9426a14e9ce0e3a2515d48f10a675ca8cb1484f388a63061d4accb82e7",
          "sha1": "1efee462da84ec5810a95e5ccb0ac7bae2faa247",
          "md5": "593eea447f2803bda7bd17130f75a5bf"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-3.2.1.jar",
          "url": "spring-amqp-3.2.1.jar",
          "size": 162345,
          "sha512": "b2d7c1b794591163fa76df4e1989fd42a4875eed08ab2a9f43e4c343118178c73f4027e69bc6180473ca3f2edfd9c26312f6cbb40858f9c1ecabe4c1ecbc50fd",
          "sha256": "0b080030af2693f689a170da0d3d9b067aa178871273cbef3f087816e976be0c",
          "sha1": "401d228d7adeb11ae037dc3bd8317feac88a8490",
          "md5": "48fdc5551c0d492d8f12241e210dc6d3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-amqp-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-3.2.1.jar",
          "url": "spring-amqp-3.2.1.jar",
          "size": 162345,
          "sha512": "b2d7c1b794591163fa76df4e1989fd42a4875eed08ab2a9f43e4c343118178c73f4027e69bc6180473ca3f2edfd9c26312f6cbb40858f9c1ecabe4c1ecbc50fd",
          "sha256": "0b080030af2693f689a170da0d3d9b067aa178871273cbef3f087816e976be0c",
          "sha1": "401d228d7adeb11ae037dc3bd8317feac88a8490",
          "md5": "48fdc5551c0d492d8f12241e210dc6d3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-amqp-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
