{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.amqp",
    "module": "spring-rabbit",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.rabbitmq",
          "module": "amqp-client",
          "version": {
            "requires": "5.22.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-3.2.1.jar",
          "url": "spring-rabbit-3.2.1.jar",
          "size": 628594,
          "sha512": "8ae9d0438f90df243b92bc7e3aacd9ee9dacdbf275813ecfccb323e3d718d8b29652cd341a6272b58aad59f67a7dbbb41da5bf001fafbd33494237d5482e41cf",
          "sha256": "76d16dcc10b5bbff0c301cf7262ffcd5c3d3ca4502a0f95c4a19a7fb02814309",
          "sha1": "7e9e37e627bfd26c0578d3fe0adc463385147425",
          "md5": "e1693b76334f034e0a761528e34d88be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.rabbitmq",
          "module": "amqp-client",
          "version": {
            "requires": "5.22.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-3.2.1.jar",
          "url": "spring-rabbit-3.2.1.jar",
          "size": 628594,
          "sha512": "8ae9d0438f90df243b92bc7e3aacd9ee9dacdbf275813ecfccb323e3d718d8b29652cd341a6272b58aad59f67a7dbbb41da5bf001fafbd33494237d5482e41cf",
          "sha256": "76d16dcc10b5bbff0c301cf7262ffcd5c3d3ca4502a0f95c4a19a7fb02814309",
          "sha1": "7e9e37e627bfd26c0578d3fe0adc463385147425",
          "md5": "e1693b76334f034e0a761528e34d88be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-rabbit-3.2.1-javadoc.jar",
          "url": "spring-rabbit-3.2.1-javadoc.jar",
          "size": 1137761,
          "sha512": "bbcba4de90fa8043a849285aefbfb7b08c2fbcab6c08d112358798d5e042fbafa807ddc2af598decd04c11a02461f69182016b8f4fa978394a2ee31357393d59",
          "sha256": "9cbaf1b4f19c0dc541fe195e0077546d000084dee56cd9f3282982a264ed6db2",
          "sha1": "c03ce8db104dfec81574c972e0d4f185b10d7a25",
          "md5": "17240feed2632d2575a8906776a38672"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-rabbit-3.2.1-sources.jar",
          "url": "spring-rabbit-3.2.1-sources.jar",
          "size": 442459,
          "sha512": "b58af897abbe1521d7536db95097b82840984d4c86ba44c83f816185a20006a559cee9412739cef239466253c9bb36b9c94f632d1054ceebfa0c0d2368e344fb",
          "sha256": "f1e4a61f4bf8501afa342357394362471787c7fb045280f86da69d02a4497749",
          "sha1": "fc401008c867040c49f04dc4ab4251eac47992f9",
          "md5": "17e1f3ea5bba1a298a5b9f26a56f6dfd"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-pool2",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-3.2.1.jar",
          "url": "spring-rabbit-3.2.1.jar",
          "size": 628594,
          "sha512": "8ae9d0438f90df243b92bc7e3aacd9ee9dacdbf275813ecfccb323e3d718d8b29652cd341a6272b58aad59f67a7dbbb41da5bf001fafbd33494237d5482e41cf",
          "sha256": "76d16dcc10b5bbff0c301cf7262ffcd5c3d3ca4502a0f95c4a19a7fb02814309",
          "sha1": "7e9e37e627bfd26c0578d3fe0adc463385147425",
          "md5": "e1693b76334f034e0a761528e34d88be"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-rabbit-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-pool2",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-3.2.1.jar",
          "url": "spring-rabbit-3.2.1.jar",
          "size": 628594,
          "sha512": "8ae9d0438f90df243b92bc7e3aacd9ee9dacdbf275813ecfccb323e3d718d8b29652cd341a6272b58aad59f67a7dbbb41da5bf001fafbd33494237d5482e41cf",
          "sha256": "76d16dcc10b5bbff0c301cf7262ffcd5c3d3ca4502a0f95c4a19a7fb02814309",
          "sha1": "7e9e37e627bfd26c0578d3fe0adc463385147425",
          "md5": "e1693b76334f034e0a761528e34d88be"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-rabbit-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
